name: macrohard
description: "By MACROHARD"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  native_device_orientation: ^2.0.3
  local_auth: ^2.1.8
  provider: ^6.1.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  volume_controller: ^2.0.7
  torch_controller: ^2.0.1
  vibration: ^1.8.4
  loading_animation_widget: ^1.2.0+4
  screen_brightness: ^1.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  percent_indicator: ^4.2.3
  email_validator: ^2.1.17
  flutter_emoji: ^2.5.1
  hive: ^2.2.3
  cloud_firestore: ^4.15.5
  carousel_slider: ^4.2.1
  confetti: ^0.7.0
  assets_audio_player: ^3.1.1
  firebase_storage: ^11.6.7
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile_placeholder.jpg
    - assets/areyousure.mp3
    - assets/hellounderwater.mp3
    - assets/bingchilling.mp3
    - assets/dadog.mp3
    - assets/emotionaldmg.mp3
    - assets/fbi.mp3

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
